Webss/Areas/CompanyArea/Controllers/QuestionBankController.cs
using Domain;
using Infras.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Webss.CustAuth;

namespace Webss.Areas.CompanyArea.Controllers
{
    [Area("CompanyArea")]
    [CompanyAuth]
    public class QuestionBankController : Controller
    {
        IQuestionBank repo;
        IQuestionDBcategory questionDBcategory;
        Icompany companyy;
        public QuestionBankController(IQuestionBank repo, IQuestionDBcategory questionDBcategory, Icompany companyy)
        {
            this.repo = repo;
            this.questionDBcategory = questionDBcategory;
            this.companyy = companyy;
        }

        public async Task< IActionResult> Index()
        {
            return View(await this.repo.GetAll());
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            ViewBag.questiondbcategories = new SelectList(await this.questionDBcategory.GetAll(), "QuestionDBCategoryID", "QuestionDBCategoryName");
            ViewBag.companies = new SelectList(await this.companyy.GetAll(), "CompanyID", "CompanyName");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(QuestionBank rec)
        {
            ViewBag.questiondbcategories= new SelectList(await this.questionDBcategory.GetAll(), "QuestionDBCategoryID", "QuestionDBCategoryName");
            ViewBag.companies = new SelectList(await this.companyy.GetAll(), "CompanyID", "CompanyName");
            if (ModelState.IsValid)
            {
                await this.repo.Create(rec);
                return RedirectToAction("Index");
            }
            return View(rec);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(Int64 id)
        {
            var rec = await this.repo.Get(id);
            ViewBag.questiondbcategories = new SelectList(await this.questionDBcategory.GetAll(), "QuestionDBCategoryID", "QuestionDBCategoryName",rec.QuestionDBCategoryID);
            ViewBag.companies = new SelectList(await this.companyy.GetAll(), "CompanyID", "CompanyName",rec.CompanyID);
            return View(rec);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(QuestionBank rec)
        {
            ViewBag.questiondbcategories = new SelectList(await this.questionDBcategory.GetAll(), "QuestionDBCategoryID", "QuestionDBCategoryName",rec.QuestionDBCategoryID);
            ViewBag.companies = new SelectList(await this.companyy.GetAll(), "CompanyID", "CompanyName",rec.CompanyID);
            if (ModelState.IsValid)
            {

                await this.repo.Update(rec);
                return RedirectToAction("Index");
            }
            return View(rec);
        }

        [HttpGet]
        public async Task<ActionResult> Delete(Int64 id)
        {
            await this.repo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Webss/Areas/CompanyArea/Views/QuestionBank/Create.cshtml
@model QuestionBank
<div class="col-6">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Create QuestionBank </h5>

            <!-- Vertical Form -->
            <form asp-action="Create" class="row g-3">
                <div class="mt-3">

                    <div class="col-12">
                        <label class="form-label">  Select QuestionDbCategory</label>
                        <select class="form-select" asp-for="QuestionDBCategoryID" asp-items="@ViewBag.questiondbcategories">
                            <option>Select QuestionDbCategory </option>
                        </select>

                    </div>
                </div>

                <div class="mt-3">

                    <div class="col-12">
                        <label class="form-label">  Select Company</label>
                        <select class="form-select" asp-for="CompanyID" asp-items="@ViewBag.companies">
                            <option>Select  Company</option>
                        </select>

                    </div>
                </div>
                <div class="col-12">
                    <label asp-for="QuestionBankTitle" class="form-label">
                    </label>
                    <input asp-for="QuestionBankTitle" class="form-control" />

                </div>

               


                <div class="mt-3">
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>
                </div>
            </form><!-- Vertical Form -->

        </div>
    </div>
</div>

Webss/Areas/CompanyArea/Views/QuestionBank/Edit.cshtml
@model QuestionBank
<div class="col-6">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Edit QuestionBank </h5>

            <!-- Vertical Form -->
            <form asp-action="Edit" class="row g-3">
                <input type="hidden" asp-for="QuestionBankID"/>
                <div class="mt-3">

                    <div class="col-12">
                        <label class="form-label">  Select QuestionDbCategory</label>
                        <select class="form-select" asp-for="QuestionDBCategoryID" asp-items="@ViewBag.questiondbcategories">
                            <option>Select QuestionDbCategory </option>
                        </select>

                    </div>
                </div>

                <div class="mt-3">

                    <div class="col-12">
                        <label class="form-label">  Select Company</label>
                        <select class="form-select" asp-for="CompanyID" asp-items="@ViewBag.companies">
                            <option>Select  Company</option>
                        </select>

                    </div>
                </div>
                <div class="col-12">
                    <label asp-for="QuestionBankTitle" class="form-label">
                    </label>
                    <input asp-for="QuestionBankTitle" class="form-control" />

                </div>

               


                <div class="mt-3">
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Update</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>
                </div>
            </form><!-- Vertical Form -->

        </div>
    </div>
</div>

Webss/Areas/CompanyArea/Views/QuestionBank/Index.cshtml
@model IEnumerable<QuestionBank>

<html>
<head>
    <title> </title>
</head>
<body>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h2 class="m-0 font-weight-bold text-primary">QuestionBank List</h2>
        </div>


        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="mt-3">
                        <a asp-action="Create" asp-controller="QuestionBank" class="btn btn-primary">  Create QuestionBank</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>QuestionBankID</th>
                                        <th>QuestionBankTitle </th>
                                        <th>QuestionDBCategoryName </th>
                                        <th>CompanyName</th>


                                    </tr>
                                </thead>


                                <tbody>
                                    @foreach (var temp in Model)
                                    {
                                        <tr>
                                            <td> @temp.QuestionBankID</td>
                                            <td> @temp.QuestionBankTitle</td>
                                            <td> @temp.QuestionDBCategory.QuestionDBCategoryName</td>
                                            <td> @temp.Company.CompanyName</td>

                                            <td>

                                                <a asp-action="Edit" asp-route-id="@temp.QuestionBankID" class="btn btn-primary"> Edit </a>
                                                <a asp-action="Delete" asp-route-id="@temp.QuestionBankID" class="btn btn-primary"> Delete </a>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</body>
</html>