Webss/Areas/SiteAdminArea/Controllers/MockTestSubjectController.cs
using Domain;
using Infras.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Webss.CustAuth;

namespace Webss.Areas.SiteAdminArea.Controllers
{
    [Area("SiteAdminArea")]
    [SiteAdminAuth]
    public class MockTestSubjectController : Controller
    {
        IMockTestCategory mockTestCategory;
        ImockTestSubject repo;
        public MockTestSubjectController(ImockTestSubject repo, IMockTestCategory mockTestCategory)
        {
            this.mockTestCategory = mockTestCategory;
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            return View(await this.repo.GetAll());
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            ViewBag.MockTestCategoryyy = new SelectList(await this.mockTestCategory.GetAll(), "MockTestCategoryID", "MockTestCategoryName");

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(MockTestSubject rec)
        {
            ViewBag.MockTestCategoryyy = new SelectList(await this.mockTestCategory.GetAll(), "MockTestCategoryID", "MockTestCategoryName");

            if (ModelState.IsValid)
            {
                await this.repo.Create(rec);
                return RedirectToAction("Index");
            }
            return View(rec);
        }


        [HttpGet]
        public async Task<ActionResult> Edit(Int64 id)
        {
            var rec = await this.repo.Get(id);
            ViewBag.MockTestCategoryyy = new SelectList(await this.mockTestCategory.GetAll(), "MockTestCategoryID", "MockTestCategoryName", rec.MockTestCategoryID);

            return View(rec);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(MockTestSubject rec)
        {
            ViewBag.MockTestCategoryyy = new SelectList(await this.mockTestCategory.GetAll(), "MockTestCategoryID", "MockTestCategoryName", rec.MockTestCategoryID);

            if (ModelState.IsValid)
            {

                await this.repo.Update(rec);
                return RedirectToAction("Index");
            }
            return View(rec);
        }

        [HttpGet]
        public async Task<ActionResult> Delete(Int64 id)
        {
            await this.repo.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Webss/Areas/SiteAdminArea/Views/MockTestSubject/Create.cshtml
@model MockTestSubject
<div class="col-6">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Create MockTestSubject </h5>

            <!-- Vertical Form -->
            <form asp-action="Create" class="row g-3">

                <div class="mt-3">

                    <div class="col-12">
                        <label class="form-label">  Select MockTestCategory</label>
                        <select class="form-select" asp-for="MockTestCategoryID" asp-items="@ViewBag.MockTestCategoryyy">
                            <option>Select MockTestCategoryCategory </option>
                        </select>

                    </div>
                </div>
                <div class="col-12">
                    <label asp-for="SubjectTitle" class="form-label">
                    </label>
                    <input asp-for="SubjectTitle" class="form-control" />

                </div>

                <div class="col-12">
                    <label asp-for="SubjectDesc" class="form-label">
                    </label>
                    <input asp-for="SubjectDesc" class="form-control" />

                </div>

               

               

                <div class="mt-3">
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>
                </div>
            </form><!-- Vertical Form -->

        </div>
    </div>
</div>

Webss/Areas/SiteAdminArea/Views/MockTestSubject/Edit.cshtml
@model MockTestSubject
<div class="col-6">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Create MockTestSubject </h5>

            <!-- Vertical Form -->
            <form asp-action="Edit" class="row g-3">
                <input type="hidden" asp-for="MockTestSubjectID"/>
                <div class="mt-3">

                    <div class="col-12">
                        <label class="form-label">  Select MockTestCategoryCategory</label>
                        <select class="form-select" asp-for="MockTestCategoryID" asp-items="@ViewBag.MockTestCategoryyy">
                            <option>Select MockTestCategoryCategory </option>
                        </select>

                    </div>
                </div>
                <div class="col-12">
                    <label asp-for="SubjectTitle" class="form-label">
                    </label>
                    <input asp-for="SubjectTitle" class="form-control" />

                </div>

                <div class="col-12">
                    <label asp-for="SubjectDesc" class="form-label">
                    </label>
                    <input asp-for="SubjectDesc" class="form-control" />

                </div>

                



                <div class="mt-3">
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>
                </div>
            </form><!-- Vertical Form -->

        </div>
    </div>
</div>

Webss/Areas/SiteAdminArea/Views/MockTestSubject/Index.cshtml
@model IEnumerable<MockTestSubject>

<html>
<head>
    <title> </title>
</head>
<body>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h2 class="m-0 font-weight-bold text-primary">MockTestSubject List</h2>
        </div>


        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="mt-3">
                        <a asp-action="Create" asp-controller="MockTestSubject" class="btn btn-primary">  Create QuestionBank</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>MockTestSubjectID</th>
                                        <th>SubjectTitle </th>
                                        <th>SubjectDesc </th>
                                        <th>MockTestCategoryName</th>


                                    </tr>
                                </thead>


                                <tbody>
                                    @foreach (var temp in Model)
                                    {
                                        <tr>
                                            <td> @temp.MockTestSubjectID</td>
                                            <td> @temp.SubjectTitle</td>
                                            <td> @temp.SubjectDesc.</td>
                                            <td> @temp.MockTestCategory.MockTestCategoryName</td>

                                            <td>

                                                <a asp-action="Edit" asp-route-id="@temp.MockTestSubjectID" class="btn btn-primary"> Edit </a>
                                                 <a asp-action="Delete" asp-route-id="@temp.MockTestSubjectID" class="btn btn-primary"> Delete </a> 
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</body>
</html>