Webss/Controllers/CompanyManageController.cs
using Domain;
using Infras;
using Infras.Dtos;
using Infras.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Webss.CustAuth;


namespace Webss.Controllers
{
    
    
    public class CompanyManageController : Controller
    {
        Icompany repo;
        Context cc;
        ITestPackage repoo;
        public CompanyManageController(Icompany repo,Context cc,ITestPackage repoo)
        {
            this.repo = repo;
            this.cc = cc;
            this.repoo = repoo;
        }
        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }


        [HttpPost]

        public async Task<IActionResult> SignIn(Logindto rec)
        {
            if (ModelState.IsValid)
            {
                var res = await this.repo.Login(rec);

                if (res.IsLoggedIn)
                {

                    var company = await this.repo.Get(res.LoggedInID);

                    if (company != null && company.ActiveFlag)
                    {

                        HttpContext.Session.SetString("LoggedInName", res.LoggedInName);
                        HttpContext.Session.SetString("CompanyID", res.LoggedInID.ToString());


                        //return RedirectToAction("Index", "CompanyHome", new { area = "CompanyArea" });
                        return RedirectToAction("Index", "Purchase");
                    }
                    else
                    {

                        ModelState.AddModelError("", "Your company is inactive. Please contact support.");
                        return View(rec);
                    }
                }


                ModelState.AddModelError("", res.Messgae);
                return View(rec);
            }

            return View(rec);
        }

        //public async Task<IActionResult> SignIn(Logindto rec)
        // {
        //     if (ModelState.IsValid)
        //     {
        //         var res = await this.repo.Login(rec);
        //         if (res.IsLoggedIn)
        //         {
        //             HttpContext.Session.SetString("LoggedInName", res.LoggedInName);
        //             HttpContext.Session.SetString("CompanyID", res.LoggedInID.ToString());
        //             return RedirectToAction("Index", "CompanyHome", new { area = "CompanyArea" });
        //         }

        //         ModelState.AddModelError("", res.Messgae);
        //         return View(rec);
        //     }
        //     return View(rec);
        // }

        [HttpGet]
        public IActionResult SignOut()
        {
            HttpContext.Session.Clear();
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            ViewBag.RegistrationDate = DateTime.Now;
            var model = new CompanyRegisterDto()
            {
                RegistrationDate = DateTime.Now
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Register(CompanyRegisterDto rec)
        {
         
            if (ModelState.IsValid)
            {
                var res = await this.repo.Register(rec);
                return View("registrationstatus",res);
            }

           
            return View(rec);
        }


        public IActionResult Index()
        {

            var testPackages = (from package in cc.testPackages
                                join detail in cc.testPackageDets on package.TestPackageID equals detail.TestPackageID
                                select new TestpackageandDetail
                                {   TestPackageID=package.TestPackageID,
                                    Price = package.Price,
                                    PackageTitle = package.PackageTitle,
                                    MaxCandidatePerExam = package.MaxCandidatePerExam,
                                 
                                    NoofTest = detail.NoofTest
                                }).ToList();

            return View(testPackages);
        }
        [HttpGet]
        public async Task<IActionResult> Detail(Int64 id)
        {
            var res = await this.repoo.GetByIDD(id);
            if (res == null)
            {
                return NotFound(); // Or handle it in a way that shows an appropriate error message to the user.
            }
            return View(res);
        }



    }
}

Webss/Controllers/PackagePurchaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace Webss.Controllers
{
    public class PackagePurchaseController : Controller
    {
        public IActionResult Buy()
        {
            return RedirectToAction("SignIn","CompanyManage",new {area=""});
        }
    }
}

Webss/Views/CompanyManage/Detail.cshtml
 @model TestPackage

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h4 class="m-0 font-weight-bold text-primary">TestPackage Details</h4>
    </div>


   


                <table class=" table table-bordered">



                   

                 
                    <tr>
                        <td> PackageTitle</td>
                        <td> @Model.PackageTitle</td>
                    </tr>
                    <tr>
                        <td> ApplicationDate</td>
                        <td> @Model.ApplicationDate</td>
                    </tr>
                    <tr>
                        <td> CreationDate</td>
                        <td> @Model.CreationDate</td>
                    </tr>
                    <tr>
                        <td> PackageDesc</td>
                        <td> @Model.PackageDesc</td>
                    </tr>
                    <tr>
                        <td> Price</td>
                        <td> @Model.Price</td>
                    </tr>

                    <tr>
                        <td> MaxCandidatePerExam</td>
                        <td> @Model.MaxCandidatePerExam</td>
                    </tr>



                </table>

                <div class="card-header py-3">
                    <h4 class="m-0 font-weight-bold text-primary">TestPackagedet Details</h4>
                </div>

                <table class=" table table-bordered">



                    <thead>
                        <tr>
                            
                            <th> NoOfTest</th>
                            <th> ValidateInMonths</th>
                        </tr>
                    </thead>

                   <tbody>
            @if (Model.TestPackageDets != null && Model.TestPackageDets.Any())
            {
                @foreach (var temp in Model.TestPackageDets)
                {
                    <tr>
                        <td>@temp.NoofTest</td>
                        <td>@temp.ValidityInMonths</td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="2">No test details available.</td>
                </tr>
            }
                   </tbody>

                </table>




            </div>
        



            @* <div>
    @await Component.InvokeAsync("OfferDiscountVC")
            </div> *@


   <div>
       <a asp-action="Index" asp-controller="CompanyManage" class="btn btn-primary" > Back </a>
       <a asp-action="Buy" asp-controller="PackagePurchase" class="btn btn-primary"> Buy</a>
   </div>

Webss/Views/CompanyManage/Index.cshtml
@model IEnumerable<TestpackageandDetail>



<div class="text-center">
    <h1 class="h4 text-black-900 mb-4">Test Packages!</h1>
</div>

            <table class="table table-bordered table-hover table-dark" width="100px">
                <thead>
                    <tr>
                        <th> PackageTitle</th>
                        <th> Price</th>
                        <th> NoofTest</th>
                        <th> MaxCandidatePerExam</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var temp in Model)
                    {
                        <tr>
                            <td> @temp.PackageTitle</td>
                            <td> @temp.Price</td>
                            <td> @temp.NoofTest</td>
                            <td> @temp.MaxCandidatePerExam</td>
                              <td>
                             <a asp-action="Detail" asp-controller="CompanyManage" asp-route-id="@temp.TestPackageID" class="btn btn-primary"> Details </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
          

Webss/Views/CompanyManage/Register.cshtml
@* @model CompanyRegisterDto
<script src="~/jquery/jquery.js"></script>
<script src="~/jquery-validate/jquery.validate.js"></script>
<script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<div class="col-5">
<div class="card">
    <div class="card-body">
        <form asp-action="Register" method="post" >
                <div asp-validation-summary="ModelOnly"> </div>
                <div class="col-12">
                    
                </div>  
                <div class="row">
                    <div class="col-12 mb-3">
                     <div class="form-label">
                            <label>CompanyName==> </label>
                     </div>
                       <div class="form-control">
                       <div class="col-md-5">
                                <input asp-for="CompanyName" placeholder="CompanyName">
                            </div>
                            <span asp-validation-for="CompanyName"> </span>
                       </div>

                    </div>
                    <div class="col-12 mb-3">
                        <label asp-for="Address">Address </label>
                        <textarea asp-for="Address" placeholder="Address" >
                </textarea>
                        <span asp-validation-for="Address" ></span>

                    </div>

                    
                    <div class="col-12 mb-3">
                        <label asp-for="EmailID"> </label>
                        <input asp-for="EmailID" placeholder="EmailID" >
                        <span asp-validation-for="EmailID"> </span>

                    </div>

                    <div class="col-12 mb-3">
                        <label asp-for="ContactPersonName"> </label>
                        <input asp-for="ContactPersonName" placeholder="ContactPersonName" >
                        <span asp-validation-for="ContactPersonName"> </span>

                    </div>

                    <div class="col-12 mb-3">
                        <label asp-for="ContactNo"> </label>
                        <input asp-for="ContactNo" placeholder="ContactNo" >
                        <span asp-validation-for="ContactNo"> </span>

                    </div>

                    <div class="col-12 mb-3">
                        <label asp-for="CompanyDesc"> </label>
                        <textarea asp-for="CompanyDesc" placeholder="Address">
                </textarea >
                        <span asp-validation-for="CompanyDesc"> </span>

                    </div>


                    <div class="col-12 mb-3">
                        <label asp-for="Password"> </label>
                        <input asp-for="Password" placeholder="Password">
                        <span asp-validation-for="Password" > </span>

                    </div>

                    <div class="col-12 mb-3">
                        <label asp-for="RegistrationDate"> </label>
                        <input asp-for="RegistrationDate" placeholder="RegistrationDate">
                        <span asp-validation-for="RegistrationDate"> </span>


                    </div>

                    <div class="col-12 mb-3">
                        <label asp-for="ActiveFlag"> </label>
                        <input asp-for="ActiveFlag" placeholder="ActiveFlag">
                        <span asp-validation-for="ActiveFlag"> </span>

                    </div>


                   

                    <div class="col-12">
                        <input type="submit" value="Save Registration" class="btn btn-danger">
                    </div>
                </div>
            </form>
    </div>
    <div>

    </div>
 *@




@model CompanyRegisterDto

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SiteAdmin 2 - Login</title>
    <script src="~/jquery/jquery.js"></script>
    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <!-- Custom fonts for this template-->
    <link href="~/backendassets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/backendassets/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome!</h1>
                                    </div>
                                    <div class="text-centre small text-danger " asp-validation-summary="ModelOnly"> </div>
                                    <form asp-action="Register" method="post">
                                        <div asp-validation-summary="ModelOnly"> </div>
                                        <div class="form-group">
                                            <b>  <label asp-for="CompanyName">CompanyName </label></b>
                                            <input type="CompanyName" class="form-control form-control-user" asp-for="CompanyName" placeholder="CompanyName" />
                                            <span class="text-danger" asp-validation-for="CompanyName"> </span>
                                       </div>

                                        <div class="form-group">
                                            <b>  <label asp-for="Address">Address </label></b>
                                            <input type="Address" class="form-control form-control-user" asp-for="Address" placeholder="Address" />
                                            <span class="text-danger" asp-validation-for="Address"> </span>
                                        </div>

                                        <div class="form-group">
                                            <b>  <label asp-for="EmailID">EmailID </label></b>
                                            <input type="EmailID" class="form-control form-control-user" asp-for="EmailID" placeholder="EmailID" />
                                            <span class="text-danger" class="text-danger" asp-validation-for="EmailID"> </span>
                                        </div>

                                        <div class="form-group">
                                            <b><label asp-for="ContactPersonName">ContactPersonName </label></b>
                                            <input type="ContactPersonName" class="form-control form-control-user" asp-for="ContactPersonName" placeholder="ContactPersonName" />
                                            <span class="text-danger" asp-validation-for="ContactPersonName"> </span>
                                        </div>


                                        <div class="form-group">
                                            <b>  <label asp-for="ContactNo">ContactNo </label></b>
                                            <input type="ContactNo" class="form-control form-control-user" asp-for="ContactNo" placeholder="ContactNo" />
                                            <span class="text-danger" asp-validation-for="ContactNo"> </span>
                                        </div>


                                        <div class="form-group">
                                            <b> <label asp-for="CompanyDesc">CompanyDesc </label></b>
                                            <input type="CompanyDesc" class="form-control form-control-user" asp-for="CompanyDesc" placeholder="CompanyDesc" />
                                            <span class="text-danger" asp-validation-for="CompanyDesc"> </span>
                                        </div>



                                        <div class="form-group">
                                            <b> <label asp-for="Password">Password </label></b>
                                            <input type="Password" class="form-control form-control-user" asp-for="Password" placeholder="Password" />
                                            <span class="text-danger" asp-validation-for="Password"> </span>
                                        </div>


                                        <div class="form-group">
                                            <b>   <label asp-for="RegistrationDate">RegistrationDate </label></b>
                                            <input type="RegistrationDate" class="form-control form-control-user" asp-for="RegistrationDate" placeholder="RegistrationDate" />
                                            <span class="text-danger" asp-validation-for="RegistrationDate"> </span>
                                        </div>

                                        <div class="form-group">
                                            <b><label asp-for="ActiveFlag">ActiveFlag </label></b>
                                            <input type="ActiveFlag" class="form-control form-control-user" asp-for="ActiveFlag" placeholder="ActiveFlag" />
                                            <span class="text-danger" asp-validation-for="ActiveFlag"> </span>
                                        </div>

                                       <div class="mt-3">
                                            <button class="btn btn-primary btn-user btn-block" type="submit">
                                                Save
                                            </button>
                                        </div>

                                    </form>
                                    <hr>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

Webss/Views/CompanyManage/SignIn.cshtml
@{
    Layout = null;
}
@model Logindto

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Company- Login</title>
    <script src="~/jquery/jquery.js"></script>
    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <!-- Custom fonts for this template-->
    <link href="~/backendassets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/backendassets/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back Company!</h1>
                                    </div>
                                    <div class="text-centre small text-danger " asp-validation-summary="ModelOnly"> </div>
                                    <form asp-action="SignIn" method="post" >
                                        <div class="form-group">
                                            <label asp-for="EmailID">EmailID </label>
                                            <input type="email" class="form-control form-control-user" asp-for="EmailID" placeholder="EmailID"/>
                                            <span asp-validation-for="EmailID" class="text-danger"> </span>
                                                
                                                 
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="Password">Password </label>
                                            <input type="password" class="form-control form-control-user" asp-for="Password" placeholder="Password" />
                                            <span asp-validation-for="Password" class="text-danger"> </span>


                                        </div>
                                     <button  class="btn btn-primary btn-user btn-block" type="submit">
                                            Login
                                        </button>
                                   
                                    </form>
                                    <hr>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

Webss/Views/CompanyManage/SignOut.cshtml
<html>
<head>
    <title> Comapny Sign out </title>
</head>
<body>
    <h1>Company  Signout </h1>
    <p>
        Your are signed out successfully!. <br />
        For Sign in again <a asp-action="SignIn" asp-controller="CompanyManage" style="color: white;"> Click Here </a> <br />

    </p>
</body>

</html>

Webss/Views/CompanyManage/registrationstatus.cshtml
@model RepoResultDto
<br />
<br />
@if (Model.IsSuccess)
{
    <div class="alert alert-danger">
        <h2> Registration Successfully </h2>
        for Login <a asp-action="SignIn"> Click Here </a>
    </div>
}
else
{
    <div class="alert alert-danger">
        <h2> Registration UnSuccessfully </h2>
        <h3> Error :@Model.Message</h3>
        <a asp-action="Register"> Go Back </a>
    </div>
}